export const CATEGORIES = [
  'Maid',
  'Cook',
  'Electrician',
  'Plumber',
  'AC Technician',
  'Carpenter',
  'Painter',
  'Driver',
  'Gardener',
  'Tailor',
  'Ironing / Press',
  'Salon / Beautician',
  'Door Rangoli',
  'Gas Repair',
  'Gas Agency',
  'Cycle Repair',
  'Washroom Cleaner',
  'Water Supply',
  'Pest Control',
  'Car Wash',
  'Milkman',
  'RO / Water Purifier',
  'Tent House',
  'Water Cans',
  'Catering',
  'Photography',
  'Decoration',
  'Boutique',
  'Movers & Packers',
  'Tutor / Home Teacher',
  'Other',
];

export type CategoryGroup = {
  id: string;
  label: string;
  categories: string[];
};

export const CATEGORY_GROUPS: CategoryGroup[] = [
  {
    id: 'home_support',
    label: 'Home Support',
    categories: [
      'Maid',
      'Cook',
      'Driver',
      'Gardener',
      'Washroom Cleaner',
      'Ironing / Press',
      'Car Wash',
      'Milkman',
      'Water Cans',
      'Water Supply',
    ],
  },
  {
    id: 'repairs',
    label: 'Repairs',
    categories: [
      'Electrician',
      'Plumber',
      'AC Technician',
      'Carpenter',
      'Painter',
      'Gas Repair',
      'Gas Agency',
      'Cycle Repair',
      'RO / Water Purifier',
      'Pest Control',
    ],
  },
  {
    id: 'personal',
    label: 'Personal',
    categories: [
      'Tailor',
      'Salon / Beautician',
      'Door Rangoli',
      'Boutique',
      'Tutor / Home Teacher',
    ],
  },
  {
    id: 'events',
    label: 'Events',
    categories: [
      'Tent House',
      'Catering',
      'Photography',
      'Decoration',
      'Movers & Packers',
    ],
  },
  {
    id: 'other',
    label: 'Other',
    categories: ['Other'],
  },
];

export const CATEGORY_COLORS: Record<string, string> = {
  Maid: '#FF6B6B',
  Cook: '#FF9F1C',
  Electrician: '#4ECDC4',
  Plumber: '#45B7D1',
  'AC Technician': '#96CEB4',
  Carpenter: '#FFEEAD',
  Painter: '#D4A5A5',
  Driver: '#2EC4B6',
  Gardener: '#22C55E',
  Tailor: '#A78BFA',
  'Ironing / Press': '#F97316',
  'Salon / Beautician': '#EC4899',
  'Door Rangoli': '#F43F5E',
  'Gas Repair': '#EF4444',
  'Gas Agency': '#DC2626',
  'Cycle Repair': '#0EA5E9',
  'Washroom Cleaner': '#06B6D4',
  'Water Supply': '#3A86FF',
  'Pest Control': '#8338EC',
  'Car Wash': '#6366F1',
  Milkman: '#F5F5DC',
  'RO / Water Purifier': '#14B8A6',
  'Tent House': '#0F766E',
  'Water Cans': '#0284C7',
  Catering: '#EA580C',
  Photography: '#1D4ED8',
  Decoration: '#F59E0B',
  Boutique: '#DB2777',
  'Movers & Packers': '#D97706',
  'Tutor / Home Teacher': '#7C3AED',
  Other: '#A0AEC0',
};
