export const CATEGORIES = [
  'Maid',
  'Cook',
  'Electrician',
  'Plumber',
  'AC Technician',
  'Carpenter',
  'Painter',
  'Driver',
  'Gardener',
  'Tailor',
  'Ironing / Press',
  'Salon / Beautician',
  'Door Rangoli',
  'Gas Repair',
  'Gas Agency',
  'Cycle Repair',
  'Car Repair',
  'Bike Repair',
  'Washroom Cleaner',
  'Water Supply',
  'Pest Control',
  'Car Wash',
  'Milkman',
  'RO / Water Purifier',
  'Grills & Mesh Work',
  'Tent House',
  'Water Cans',
  'Catering',
  'Photography',
  'Decoration',
  'Boutique',
  'Movers & Packers',
  'Teaching',
  'RTO Agent',
  'Aadhar Centre',
  // New Categories
  'Pandit / Pujari',
  'Mosquito Net / Screens',
  'Balcony Safety Nets',
  'Blinds & Curtains',
  'Core Cutting',
  'False Ceiling / POP',
  'Marble & Granite Work',
  'Balcony Cloth Hangers',
  'Internet Provider / Tech',
  'Washing Machine Repair',
  'TV Repair & Install',
  'Swimming / Fitness Coach',
  'Doctor / Clinic',
  'Pharmacy Delivery',
  'Diagnostics / Lab Tests',
  'Physiotherapy',
  'Home Nurse / Nanny',
  'Other',
];

export type CategoryGroup = {
  id: string;
  label: string;
  categories: string[];
};

export const CATEGORY_GROUPS: CategoryGroup[] = [
  {
    id: 'home_support',
    label: 'Home Support',
    categories: [
      'Maid',
      'Cook',
      'Gardener',
      'Washroom Cleaner',
      'Ironing / Press',
      'Milkman',
      'Water Cans',
      'Water Supply',
    ],
  },
  {
    id: 'repairs',
    label: 'Repairs & Maintenance',
    categories: [
      'Electrician',
      'Plumber',
      'AC Technician',
      'Carpenter',
      'Painter',
      'Gas Repair',
      'Gas Agency',
      'RO / Water Purifier',
      'Pest Control',
      'Grills & Mesh Work',
      // New repairs
      'Mosquito Net / Screens',
      'Balcony Safety Nets',
      'Blinds & Curtains',
      'Core Cutting',
      'False Ceiling / POP',
      'Marble & Granite Work',
      'Balcony Cloth Hangers',
      'Internet Provider / Tech',
      'Washing Machine Repair',
      'TV Repair & Install',
    ],
  },
  {
    id: 'healthcare',
    label: 'Healthcare & Wellness',
    categories: [
      'Doctor / Clinic',
      'Pharmacy Delivery',
      'Diagnostics / Lab Tests',
      'Physiotherapy',
      'Home Nurse / Nanny',
    ],
  },
  {
    id: 'personal',
    label: 'Personal Care',
    categories: [
      'Tailor',
      'Salon / Beautician',
      'Door Rangoli',
      'Boutique',
      'Pandit / Pujari',
    ],
  },
  {
    id: 'transport',
    label: 'Transport & Vehicle Care',
    categories: [
      'Driver',
      'Car Repair',
      'Bike Repair',
      'Cycle Repair',
      'Car Wash',
    ],
  },
  {
    id: 'events',
    label: 'Events & Occasions',
    categories: [
      'Tent House',
      'Catering',
      'Photography',
      'Decoration',
      'Movers & Packers',
    ],
  },
  {
    id: 'education',
    label: 'Education & Coaching',
    categories: ['Teaching', 'Swimming / Fitness Coach'],
  },
  {
    id: 'govt_docs',
    label: 'Government & Docs',
    categories: [
      'RTO Agent',
      'Aadhar Centre',
    ],
  },
  {
    id: 'other',
    label: 'Other',
    categories: ['Other'],
  },
];

export const CATEGORY_COLORS: Record<string, string> = {
  Maid: '#FF6B6B',
  Cook: '#FF9F1C',
  Electrician: '#4ECDC4',
  Plumber: '#45B7D1',
  'AC Technician': '#96CEB4',
  Carpenter: '#FFEEAD',
  Painter: '#D4A5A5',
  Driver: '#2EC4B6',
  Gardener: '#22C55E',
  Tailor: '#A78BFA',
  'Ironing / Press': '#F97316',
  'Salon / Beautician': '#EC4899',
  'Door Rangoli': '#F43F5E',
  'Gas Repair': '#EF4444',
  'Gas Agency': '#DC2626',
  'Cycle Repair': '#0EA5E9',
  'Car Repair': '#2563EB',
  'Bike Repair': '#1D4ED8',
  'Washroom Cleaner': '#06B6D4',
  'Water Supply': '#3A86FF',
  'Pest Control': '#8338EC',
  'Car Wash': '#6366F1',
  Milkman: '#F5F5DC',
  'RO / Water Purifier': '#14B8A6',
  'Grills & Mesh Work': '#0D9488',
  'Tent House': '#0F766E',
  'Water Cans': '#0284C7',
  Catering: '#EA580C',
  Photography: '#1D4ED8',
  Decoration: '#F59E0B',
  Boutique: '#DB2777',
  'Movers & Packers': '#D97706',
  Teaching: '#7C3AED',
  'RTO Agent': '#0369A1',
  'Aadhar Centre': '#0891B2',
  'Pandit / Pujari': '#EAB308',
  'Mosquito Net / Screens': '#10B981',
  'Balcony Safety Nets': '#3B82F6',
  'Blinds & Curtains': '#6366F1',
  'Core Cutting': '#6B7280',
  'False Ceiling / POP': '#8B5CF6',
  'Marble & Granite Work': '#4B5563',
  'Balcony Cloth Hangers': '#F43F5E',
  'Internet Provider / Tech': '#06B6D4',
  'Washing Machine Repair': '#3B82F6',
  'TV Repair & Install': '#EC4899',
  'Swimming / Fitness Coach': '#14B8A6',
  'Doctor / Clinic': '#EF4444',
  'Pharmacy Delivery': '#F43F5E',
  'Diagnostics / Lab Tests': '#8B5CF6',
  'Physiotherapy': '#10B981',
  'Home Nurse / Nanny': '#3B82F6',
  Other: '#A0AEC0',
};
