export const CATEGORIES = [
  'Maid',
  'Cook',
  'Electrician',
  'Plumber',
  'AC Technician',
  'Carpenter',
  'Painter',
  'Driver',
  'Gardener',
  'Tailor',
  'Ironing / Press',
  'Salon / Beautician',
  'Door Rangoli',
  'Gas Repair',
  'Gas Agency',
  'Cycle Repair',
  'Washroom Cleaner',
  'Water Supply',
  'Pest Control',
  'Car Wash',
  'Milkman',
  'RO / Water Purifier',
  'Movers & Packers',
  'Tutor / Home Teacher',
  'Other',
];

export const CATEGORY_COLORS: Record<string, string> = {
  Maid: '#FF6B6B',
  Cook: '#FF9F1C',
  Electrician: '#4ECDC4',
  Plumber: '#45B7D1',
  'AC Technician': '#96CEB4',
  Carpenter: '#FFEEAD',
  Painter: '#D4A5A5',
  Driver: '#2EC4B6',
  Gardener: '#22C55E',
  Tailor: '#A78BFA',
  'Ironing / Press': '#F97316',
  'Salon / Beautician': '#EC4899',
  'Door Rangoli': '#F43F5E',
  'Gas Repair': '#EF4444',
  'Gas Agency': '#DC2626',
  'Cycle Repair': '#0EA5E9',
  'Washroom Cleaner': '#06B6D4',
  'Water Supply': '#3A86FF',
  'Pest Control': '#8338EC',
  'Car Wash': '#6366F1',
  Milkman: '#F5F5DC',
  'RO / Water Purifier': '#14B8A6',
  'Movers & Packers': '#D97706',
  'Tutor / Home Teacher': '#7C3AED',
  Other: '#A0AEC0',
};
