export const APP_EMOJIS = {
  home: '🏠',
  favoritesFilled: '❤️',
  favoritesEmpty: '🤍',
  funds: '💰',
  profile: '👤',
  back: '←',
  search: '🔍',
  settings: '⚙️',
  notifications: '🔔',
  chevronRight: '→',
  add: '+',
  close: '✕',
  call: '📞',
  whatsapp: '💬',
  verified: '✅',
  starFilled: '★',
  starHalf: '⯨',
  starEmpty: '☆',
  photo: '📷',
  share: '📤',
  contribution: '💚',
  expense: '📤',
  wallet: '💰',
  fundActive: '🟢',
  community: '🏘️',
  house: '🏡',
  members: '👥',
  admin: '🛡️',
  treasurer: '💼',
  collector: '📋',
  resident: '🏠',
  success: '✅',
  warning: '⚠️',
  error: '❌',
  info: 'ℹ️',
  loading: '⏳',
  mail: '✉️',
  lock: '🔒',
  visible: '👁️',
  hidden: '🙈',
  google: 'G',
} as const;

const SERVICE_CATEGORY_EMOJIS: Record<string, string> = {
  plumber: '🔧',
  electrician: '⚡',
  carpenter: '🪵',
  carpentry: '🪵',
  cleaner: '🧹',
  cleaning: '🧹',
  maid: '🧹',
  painter: '🎨',
  painting: '🎨',
  cook: '🍳',
  cooking: '🍳',
  chef: '🍳',
  driver: '🚗',
  driving: '🚗',
  chauffeur: '🚗',
  delivery: '📦',
  cctv: '📷',
  camera: '📷',
  photography: '📷',
  photographer: '📷',
  decoration: '🎈',
  decorator: '🎈',
  'ac repair': '❄️',
  'ac technician': '❄️',
  'ac service': '❄️',
  gardener: '🌱',
  garden: '🌱',
  tailor: '✂️',
  'ironing / press': '👔',
  ironing: '👔',
  press: '👔',
  dhobi: '👔',
  'salon / beautician': '💇',
  salon: '💇',
  beautician: '💇',
  'door rangoli': '🎨',
  rangoli: '🎨',
  'gas repair': '🔥',
  'gas agency': '⛽',
  'cycle repair': '🚲',
  'washroom cleaner': '🚿',
  'water supply': '💧',
  'pest control': '🐛',
  'car wash': '🚗',
  milkman: '🥛',
  milk: '🥛',
  'ro / water purifier': '💧',
  'water purifier': '💧',
  'movers & packers': '📦',
  movers: '📦',
  packers: '📦',
  'tutor / home teacher': '📚',
  tutor: '📚',
  teacher: '📚',
};

export const getServiceCategoryEmoji = (category?: string | null) => {
  if (!category) {
    return '🛠️';
  }

  const normalized = category.trim().toLowerCase();
  return SERVICE_CATEGORY_EMOJIS[normalized] ?? '🛠️';
};